apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-argocd 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  nginx-argocd
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60

