apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-argocd
    namespace: dev
  name: nginx-argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-argocd
  template:
    metadata:
      labels:
        app: nginx-argocd
    spec:
      containers:
      - image: nginx
        name: nginx-argocd

