apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: http-test-kustomize
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-test-kustomize
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60

